import type { AlertEvent, Vehicle } from '../types/fleet';

const API_BASE_URL = (import.meta.env.VITE_API_URL || '/api/v1').replace(/\/$/, '');
const TOKEN_KEY = 'qts_govfleet_access_token';
export type ApiUser = { id:string; username:string; email:string; fullName:string; agencyId:string|null; departmentId:string|null; driverId:string|null; roles:string[]; permissions:string[] };
export type VehicleApiRow = { id:string; registration_number:string; asset_number:string|null; make:string|null; model:string|null; model_year:number|null; vehicle_type:string|null; fuel_type:string|null; tank_capacity_litres:number|null; odometer_km:number; status:string; agency_id:string; agency_name:string; department_id:string|null; department_name:string|null };
export type VehicleListResponse={data:VehicleApiRow[];pagination:{page:number;limit:number;total:number;pages:number}};
export type AlertListResponse={data:AlertEvent[];pagination:{page:number;limit:number;total:number;pages:number}};
export type DriverApiRow={id:string;employee_number:string|null;full_name:string;phone:string|null;licence_number:string|null;licence_expiry:string|null;active:boolean};
export type DriverAssignment={id:string;vehicle_id:string;driver_id:string;starts_at:string;ends_at:string|null;assigned_by:string|null;started:boolean;active:boolean;employee_number:string|null;full_name:string;phone:string|null;licence_number:string|null;licence_expiry:string|null};
export type DriverListResponse={data:DriverApiRow[]}; export type DriverAssignmentResponse={data:DriverAssignment[]};
export type DeviceApiRow={id:string;device_identifier:string;serial_number:string|null;manufacturer:string|null;model:string|null;protocol:string|null;firmware_version:string|null;status:string;last_heartbeat_at:string|null;vehicle_id:string;registration_number:string;starts_at:string;ends_at:string|null};
export type DeviceResponse={data:DeviceApiRow};
export type TripApiRow={id:string;vehicle_id:string;driver_id:string|null;started_at:string;ended_at:string|null;start_lat:number|null;start_lng:number|null;end_lat:number|null;end_lng:number|null;distance_km:number|string;duration_seconds:number|string;idle_seconds:number|string;max_speed_kmh:number|string|null;average_speed_kmh:number|string|null;fuel_consumed_litres:number|string|null;registration_number:string;asset_number:string|null;driver_name:string|null};
export type TripPointApiRow={id:number;telemetry_id:number;recorded_at:string;latitude:number;longitude:number;speed_kmh:number|string|null;ignition:boolean|null;fuel_litres:number|string|null}; export type TripDetailApiRow=TripApiRow&{points:TripPointApiRow[]}; export type TripListResponse={data:TripApiRow[];pagination:{page:number;limit:number;total:number;pages:number}};
export type FuelTransaction={id:string;vehicle_id:string;driver_id:string|null;transaction_type:'refuel'|'adjustment';occurred_at:string;odometer_km:number|string|null;fuel_before_litres:number|string|null;fuel_after_litres:number|string|null;quantity_litres:number|string;price_per_litre:number|string|null;total_cost:number|string;station_name:string|null;receipt_reference:string|null;notes:string|null;created_by:string|null};
export type FuelAnomaly={id:string;vehicle_id?:string;registration_number?:string;anomaly_type:'sudden_drop'|'abnormal_consumption'|'refuel_mismatch';occurred_at:string;litres_delta:number|string|null;expected_litres:number|string|null;severity:string;metadata:Record<string,unknown>;resolved_at:string|null}; export type FuelVehicleResponse={data:{vehicle:{id:string;registration_number:string;tank_capacity_litres:number|null};transactions:FuelTransaction[];anomalies:FuelAnomaly[];month:{litres:number|string;cost:number|string;transactions:number|string}}}; export type FuelSummaryResponse={data:{transactions:number;litres:number|string;cost:number|string;vehicles:number;open_anomalies:number;anomalies:number}};
export type MaintenanceRecord={id:string;vehicle_id:string;registration_number:string;category:string;status:'scheduled'|'in_progress'|'completed'|'cancelled'|'overdue'|'due_soon';priority:'low'|'medium'|'high'|'critical';due_at:string|null;due_odometer_km:number|string|null;performed_at:string|null;odometer_km:number|string|null;estimated_cost:number|string|null;actual_cost:number|string|null;service_provider:string|null;notes:string|null;interval_km:number|string|null;interval_days:number|null;completed_by:string|null;created_at:string;updated_at:string}; export type MaintenanceSummary={total:number;overdue:number;due_soon:number;scheduled:number;in_progress:number;completed:number;cost:number|string};
export type DriverSafetyRow={driver_id:string;full_name:string;employee_number:string|null;phone:string|null;licence_number:string|null;vehicle_id:string|null;registration_number:string|null;status:string|null;event_count:number;overspeed_count:number;harsh_braking_count:number;harsh_acceleration_count:number;after_hours_count:number;serious_event_count:number;safety_score:number;grade:'A'|'B'|'C'|'warning'};
export function getAccessToken(){return sessionStorage.getItem(TOKEN_KEY)} export function setAccessToken(token:string){sessionStorage.setItem(TOKEN_KEY,token)} export function clearAccessToken(){sessionStorage.removeItem(TOKEN_KEY)}
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);headers.set('Accept','application/json');if(init.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');const token=getAccessToken();if(token)headers.set('Authorization',`Bearer ${token}`);const response=await fetch(`${API_BASE_URL}${path}`,{...init,headers});if(response.status===401)clearAccessToken();if(!response.ok)throw new Error((await response.text())||`API request failed (${response.status})`);if(response.status===204)return undefined as T;return response.json() as Promise<T>}
export async function login(username:string,password:string){const result=await request<{token:string;expiresAt:string;user:ApiUser}>('/auth/login',{method:'POST',body:JSON.stringify({username,password})});setAccessToken(result.token);return result} export async function getCurrentUser(){return(await request<{user:ApiUser}>('/auth/me')).user} export async function logout(){try{await request<void>('/auth/logout',{method:'POST'})}finally{clearAccessToken()}}
export async function getVehicles(params:{page?:number;limit?:number;search?:string;status?:string}={}){const q=new URLSearchParams();if(params.page)q.set('page',String(params.page));if(params.limit)q.set('limit',String(params.limit));if(params.search)q.set('search',params.search);if(params.status)q.set('status',params.status);return request<VehicleListResponse>(`/vehicles?${q}`)} export async function getLatestTelemetry(){return request<{data:Array<Record<string,unknown>>}>('/telemetry/latest')} export async function getAlerts(params:{page?:number;limit?:number;severity?:string;acknowledged?:boolean;vehicleId?:string}={}){const q=new URLSearchParams();if(params.page)q.set('page',String(params.page));if(params.limit)q.set('limit',String(params.limit));if(params.severity)q.set('severity',params.severity);if(params.acknowledged!==undefined)q.set('acknowledged',String(params.acknowledged));if(params.vehicleId)q.set('vehicleId',params.vehicleId);return request<AlertListResponse>(`/alerts?${q}`)} export async function getAlertSummary(){return request<{total:number;unacknowledged:number;critical:number;high:number;medium:number;low:number}>('/alerts/summary')} export async function acknowledgeAlert(id:string){return request(`/alerts/${encodeURIComponent(id)}/acknowledge`,{method:'POST'})}
export async function getDrivers(search=''){const q=new URLSearchParams();if(search.trim())q.set('search',search.trim());return request<DriverListResponse>(`/drivers${q.toString()?`?${q}`:''}`)} export async function getVehicleDriverAssignments(vehicleId:string){return request<DriverAssignmentResponse>(`/assignments/vehicles/${encodeURIComponent(vehicleId)}`)} export async function assignDriverToVehicle(vehicleId:string,driverId:string,startsAt?:string,endsAt?:string){return request<{data:DriverAssignment}>(`/assignments/vehicles/${encodeURIComponent(vehicleId)}/driver`,{method:'POST',body:JSON.stringify({driverId,...(startsAt?{startsAt}:{}),...(endsAt?{endsAt}:{})})})} export async function endDriverVehicleAssignment(assignmentId:string,endsAt?:string){return request<{data:DriverAssignment}>(`/assignments/${encodeURIComponent(assignmentId)}/end`,{method:'POST',body:JSON.stringify(endsAt?{endsAt}:{})})} export async function getVehicleDevice(vehicleId:string){return(await request<DeviceResponse>(`/devices/vehicles/${encodeURIComponent(vehicleId)}`)).data}
export async function getTrips(params:{page?:number;limit?:number;vehicleId?:string;from?:string;to?:string;status?:'open'|'completed'}={}){const q=new URLSearchParams();if(params.page)q.set('page',String(params.page));if(params.limit)q.set('limit',String(params.limit));if(params.vehicleId)q.set('vehicleId',String(params.vehicleId));if(params.from)q.set('from',params.from);if(params.to)q.set('to',params.to);if(params.status)q.set('status',params.status);return request<TripListResponse>(`/trips?${q}`)} export async function getTrip(id:string){return(await request<{data:TripDetailApiRow}>(`/trips/${encodeURIComponent(id)}`)).data} export async function closeTrip(id:string){return request<{data:TripApiRow}>(`/trips/${encodeURIComponent(id)}/close`,{method:'POST'})}
export async function getVehicleFuel(vehicleId:string){return request<FuelVehicleResponse>(`/fuel/vehicles/${encodeURIComponent(vehicleId)}`)} export async function getFuelSummary(params:{from?:string;to?:string}={}){const q=new URLSearchParams();if(params.from)q.set('from',params.from);if(params.to)q.set('to',params.to);return request<FuelSummaryResponse>(`/fuel/summary?${q}`)} export async function getFuelAnomalies(params:{limit?:number;resolved?:boolean}={}){const q=new URLSearchParams();if(params.limit)q.set('limit',String(params.limit));if(params.resolved!==undefined)q.set('resolved',String(params.resolved));return request<{data:FuelAnomaly[]}>(`/fuel/anomalies?${q}`)} export async function resolveFuelAnomaly(id:string){return request<{data:FuelAnomaly}>(`/fuel/anomalies/${encodeURIComponent(id)}/resolve`,{method:'POST'})} export async function createFuelRefuel(vehicleId:string,input:{quantityLitres:number;pricePerLitre?:number;occurredAt?:string;odometerKm?:number;fuelBeforeLitres?:number;fuelAfterLitres?:number;stationName?:string;receiptReference?:string;notes?:string}){return request<{data:FuelTransaction}>(`/fuel/vehicles/${encodeURIComponent(vehicleId)}/refuels`,{method:'POST',body:JSON.stringify(input)})}
export async function getMaintenance(params:{status?:string;vehicleId?:string;limit?:number}={}){const q=new URLSearchParams();if(params.status)q.set('status',params.status);if(params.vehicleId)q.set('vehicleId',params.vehicleId);if(params.limit)q.set('limit',String(params.limit));return request<{data:MaintenanceRecord[]}>(`/maintenance?${q}`)} export async function getMaintenanceSummary(){return request<{data:MaintenanceSummary}>('/maintenance/summary')} export async function createMaintenance(input:{vehicleId:string;category:string;dueAt?:string;dueOdometerKm?:number;estimatedCost?:number;serviceProvider?:string;notes?:string;priority?:MaintenanceRecord['priority'];intervalKm?:number;intervalDays?:number}){return request<{data:MaintenanceRecord}>('/maintenance',{method:'POST',body:JSON.stringify(input)})} export async function setMaintenanceStatus(id:string,status:MaintenanceRecord['status']){return request<{data:MaintenanceRecord}>(`/maintenance/${encodeURIComponent(id)}/status`,{method:'PATCH',body:JSON.stringify({status})})} export async function completeMaintenance(id:string,input:{actualCost?:number;performedAt?:string;odometerKm?:number;notes?:string}={}){return request<{data:MaintenanceRecord}>(`/maintenance/${encodeURIComponent(id)}/complete`,{method:'PATCH',body:JSON.stringify(input)})}
export async function getDriverSafety(){return request<{data:DriverSafetyRow[];periodDays:number}>('/intelligence/drivers')}
export function mapVehicle(row:VehicleApiRow,telemetry?:Record<string,unknown>):Vehicle{const fuelType=row.fuel_type==='Petrol'?'Petrol':'Diesel';const status=['moving','stopped','idling','parked','offline','no_gps','emergency','unauthorized'].includes(row.status)?row.status as Vehicle['status']:'offline';const department=row.department_name||row.agency_name;const lat=Number(telemetry?.latitude??0),lng=Number(telemetry?.longitude??0),speed=Number(telemetry?.speed_kmh??0),tank=Number(row.tank_capacity_litres??0),fuel=Number(telemetry?.fuel_litres??0);return {id:row.id,regNumber:row.registration_number,assetNumber:row.asset_number||'',make:row.make||'',model:row.model||'',year:row.model_year||new Date().getFullYear(),type:(row.vehicle_type||'Utility Pickup') as Vehicle['type'],department:department as Vehicle['department'],assignedDriver:{id:'',name:'Unassigned',phone:'',licenseNumber:'',safetyScore:0},deviceId:'',simNumber:'',fuelType,tankCapacityLiters:tank,currentFuelLiters:fuel,currentFuelPercentage:tank>0?Math.round(fuel/tank*100):0,mileageKm:Number(telemetry?.odometer_km??row.odometer_km??0),status,currentLocation:{lat,lng,address:''},speedKmh:speed,heading:Number(telemetry?.heading??0),ignition:typeof telemetry?.ignition==='boolean'?telemetry.ignition:false,gpsStatus:telemetry?'Connected':'Offline',satellites:Number(telemetry?.satellites??0),gsmSignal:Number(telemetry?.gsm_signal??0),lastCommunication:String(telemetry?.recorded_at??''),batteryVoltage:Number(telemetry?.battery_voltage??0),insuranceExpiry:'',registrationExpiry:'',nextServiceKm:0,lastServiceDate:'',dailyKm:0,workingHoursToday:0,idleHoursToday:0,afterHoursUsageDetected:false}}
export type FleetEvent={type:'connected'|'telemetry.updated'|'alert.created'|'vehicle.updated';occurredAt:string;payload:Record<string,unknown>};
export function subscribeToFleetEvents(onEvent:(event:FleetEvent)=>void,onError?:(error:Error)=>void){const controller=new AbortController(),token=getAccessToken();if(!token){onError?.(new Error('Authentication required for realtime events'));return()=>controller.abort();}void(async()=>{try{const response=await fetch(`${API_BASE_URL}/realtime/events`,{headers:{Accept:'text/event-stream',Authorization:`Bearer ${token}`},signal:controller.signal});if(!response.ok||!response.body)throw new Error(`Realtime connection failed (${response.status})`);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(!controller.signal.aborted){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const frames=buffer.split('\n\n');buffer=frames.pop()??'';for(const frame of frames){const data=frame.split('\n').filter(line=>line.startsWith('data:')).map(line=>line.slice(5).trim()).join('\n');if(!data)continue;try{onEvent(JSON.parse(data) as FleetEvent)}catch{}}}}catch(error){if(!controller.signal.aborted)onError?.(error instanceof Error?error:new Error(String(error)))}})();return()=>controller.abort()}
