import React, { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, BarChart3, Calculator, Fuel, RefreshCw, TrendingDown, TrendingUp, WalletCards, Wrench } from 'lucide-react';
import { getCostSummary, getRoi, getVehicleCosts, type CostSummary, type RoiResult, type VehicleCost } from '../services/costApi';

const money=(v:number|string)=>`GMD ${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;
const num=(v:number|string)=>Number(v||0);
function Card({label,value,icon:Icon}:{label:string;value:React.ReactNode;icon:React.ElementType}){return <div className="rounded-xl border border-slate-800 bg-slate-950 p-4"><div className="flex items-center gap-2 text-[10px] uppercase font-semibold text-slate-500"><Icon className="w-4 h-4 text-cyan-400"/>{label}</div><div className="mt-2 text-xl font-mono font-bold text-white">{value}</div></div>}

export const CostFinancialView:React.FC=()=>{
 const [summary,setSummary]=useState<CostSummary|null>(null); const [vehicles,setVehicles]=useState<VehicleCost[]>([]); const [roi,setRoi]=useState<RoiResult|null>(null); const [baseline,setBaseline]=useState(''); const [implementation,setImplementation]=useState(''); const [roiLoading,setRoiLoading]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [roiError,setRoiError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const [s,v]=await Promise.all([getCostSummary(),getVehicleCosts()]);setSummary(s.data);setVehicles(v.data);}catch(e){setError(e instanceof Error?e.message:'Unable to load cost intelligence');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const calculateRoi=async()=>{const baselineAnnualCost=Number(baseline);const implementationCost=Number(implementation);if(!Number.isFinite(baselineAnnualCost)||baselineAnnualCost<0){setRoiError('Enter a valid non-negative annual baseline cost.');return;}if(!Number.isFinite(implementationCost)||implementationCost<=0){setRoiError('Enter an implementation cost greater than zero.');return;}setRoiLoading(true);setRoiError('');try{const result=await getRoi({baselineAnnualCost,implementationCost});setRoi(result.data);}catch(e){setRoiError(e instanceof Error?e.message:'Unable to calculate ROI');setRoi(null);}finally{setRoiLoading(false);}};
 const top=useMemo(()=>vehicles.slice(0,10),[vehicles]);
 const roiPositive=roi?.positiveRoi;
 return <div className="h-full overflow-y-auto p-4 sm:p-6 space-y-5 bg-slate-900 text-slate-100">
  <div className="flex items-center justify-between gap-3"><div><h1 className="text-xl font-bold text-white">Cost & Financial Intelligence</h1><p className="text-xs text-slate-400 mt-1">Fleet operating cost, financial control and return-on-investment intelligence.</p></div><button onClick={()=>void load()} disabled={loading} className="flex items-center gap-2 px-3 py-2 rounded-lg border border-slate-700 bg-slate-950 text-xs font-semibold text-slate-200 disabled:opacity-50"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>Refresh</button></div>
  {error&&<div className="rounded-lg border border-red-800 bg-red-950/30 px-3 py-2 text-xs text-red-300">{error}</div>}
  {!summary&&loading?<div className="text-sm text-slate-500">Loading financial intelligence…</div>:summary&&<>
   <div className="grid grid-cols-2 lg:grid-cols-5 gap-3"><Card label="Total cost" value={money(summary.total_cost)} icon={BarChart3}/><Card label="Fuel cost" value={money(summary.fuel_cost)} icon={Fuel}/><Card label="Maintenance cost" value={money(summary.maintenance_cost)} icon={Wrench}/><Card label="Distance" value={`${summary.distance_km.toLocaleString()} km`} icon={Activity}/><Card label="Cost / km" value={money(summary.cost_per_km)} icon={BarChart3}/></div>
   <section className="rounded-xl border border-slate-800 bg-slate-950 overflow-hidden">
    <div className="p-4 border-b border-slate-800 flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Calculator className="w-4 h-4 text-cyan-400"/><h2 className="text-xs font-bold uppercase tracking-wider text-white">ROI Engine</h2></div><p className="text-[11px] text-slate-500 mt-1">Compare the fleet's annual baseline cost with the annualized recorded operating cost.</p></div>{roi&&<span className={`px-2 py-1 rounded-full text-[10px] font-bold uppercase ${roiPositive?'bg-emerald-950 text-emerald-300':'bg-red-950 text-red-300'}`}>{roiPositive?'Positive ROI':'Negative ROI'}</span>}</div>
    <div className="p-4 grid grid-cols-1 xl:grid-cols-3 gap-4">
      <div className="rounded-lg border border-slate-800 bg-slate-900/70 p-4 space-y-3"><div><label className="text-[10px] uppercase font-semibold text-slate-500">Annual baseline cost</label><div className="mt-1 flex items-center rounded-lg border border-slate-700 bg-slate-950"><span className="px-3 text-xs text-slate-500">GMD</span><input value={baseline} onChange={e=>setBaseline(e.target.value)} inputMode="decimal" placeholder="e.g. 1000000" className="w-full bg-transparent px-2 py-2 text-sm font-mono text-white outline-none"/></div></div><div><label className="text-[10px] uppercase font-semibold text-slate-500">Implementation cost</label><div className="mt-1 flex items-center rounded-lg border border-slate-700 bg-slate-950"><span className="px-3 text-xs text-slate-500">GMD</span><input value={implementation} onChange={e=>setImplementation(e.target.value)} inputMode="decimal" placeholder="e.g. 500000" className="w-full bg-transparent px-2 py-2 text-sm font-mono text-white outline-none"/></div></div><button onClick={()=>void calculateRoi()} disabled={roiLoading} className="w-full rounded-lg bg-cyan-600 px-4 py-2 text-xs font-bold text-white hover:bg-cyan-500 disabled:opacity-50">{roiLoading?'Calculating…':'Calculate ROI'}</button>{roiError&&<div className="text-[11px] text-red-300">{roiError}</div>}</div>
      <div className="xl:col-span-2 grid grid-cols-2 lg:grid-cols-4 gap-3">
       <div className="rounded-lg border border-slate-800 bg-slate-900/70 p-4"><div className="text-[10px] uppercase text-slate-500">Annualized current cost</div><div className="mt-2 text-lg font-mono font-bold text-white">{roi?money(roi.annualizedCurrentCost):'—'}</div></div>
       <div className="rounded-lg border border-slate-800 bg-slate-900/70 p-4"><div className="text-[10px] uppercase text-slate-500">Annual savings</div><div className="mt-2 flex items-center gap-2 text-lg font-mono font-bold text-white">{roi?(roi.annualSavings>=0?<TrendingDown className="w-5 h-5 text-emerald-400"/>:<TrendingUp className="w-5 h-5 text-red-400"/>):null}{roi?money(roi.annualSavings):'—'}</div></div>
       <div className="rounded-lg border border-slate-800 bg-slate-900/70 p-4"><div className="text-[10px] uppercase text-slate-500">ROI</div><div className={`mt-2 text-lg font-mono font-bold ${roi?(roi.roiPercent>=0?'text-emerald-300':'text-red-300'):'text-white'}`}>{roi?`${roi.roiPercent.toLocaleString(undefined,{maximumFractionDigits:2})}%`:'—'}</div></div>
       <div className="rounded-lg border border-slate-800 bg-slate-900/70 p-4"><div className="text-[10px] uppercase text-slate-500">Payback period</div><div className="mt-2 text-lg font-mono font-bold text-white">{roi?.paybackMonths!=null?`${roi.paybackMonths.toLocaleString(undefined,{maximumFractionDigits:1})} mo`:'—'}</div></div>
      </div>
    </div>
    {roi&&<div className="px-4 pb-4 grid grid-cols-1 md:grid-cols-3 gap-3"><div className="rounded-lg bg-slate-900/60 p-3"><div className="text-[10px] uppercase text-slate-500">Observed cost</div><div className="mt-1 font-mono font-semibold text-white">{money(roi.observedCost)}</div></div><div className="rounded-lg bg-slate-900/60 p-3"><div className="text-[10px] uppercase text-slate-500">Net annual benefit</div><div className="mt-1 font-mono font-semibold text-white">{money(roi.netAnnualBenefit)}</div></div><div className="rounded-lg bg-slate-900/60 p-3"><div className="text-[10px] uppercase text-slate-500">Actual fuel / maintenance</div><div className="mt-1 font-mono font-semibold text-white">{money(roi.fuelActual)} / {money(roi.maintenanceActual)}</div></div></div>}
   </section>
   <div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><div className="rounded-xl border border-slate-800 bg-slate-950 p-4"><div className="text-[10px] uppercase text-slate-500">Fuel efficiency cost</div><div className="mt-2 text-lg font-mono font-bold text-white">{money(summary.fuel_cost_per_km)} / km</div><div className="mt-1 text-xs text-slate-500">{summary.fuel_litres.toLocaleString()} litres recorded</div></div><div className="rounded-xl border border-slate-800 bg-slate-950 p-4"><div className="text-[10px] uppercase text-slate-500">Maintenance cost / km</div><div className="mt-2 text-lg font-mono font-bold text-white">{money(summary.maintenance_cost_per_km)} / km</div></div><div className="rounded-xl border border-slate-800 bg-slate-950 p-4"><div className="text-[10px] uppercase text-slate-500">Open fuel anomalies</div><div className="mt-2 flex items-center gap-2 text-lg font-mono font-bold text-white"><AlertTriangle className="w-5 h-5 text-amber-400"/>{summary.open_fuel_anomalies}</div></div></div>
   <section className="rounded-xl border border-slate-800 bg-slate-950 overflow-hidden"><div className="p-4 border-b border-slate-800"><h2 className="text-xs font-bold uppercase tracking-wider text-white">Vehicle cost ranking</h2></div>{top.length===0?<div className="p-4 text-xs text-slate-500">No recorded cost data yet.</div>:<div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="text-left text-[10px] uppercase text-slate-500 border-b border-slate-800"><th className="p-3">Vehicle</th><th className="p-3">Distance</th><th className="p-3">Fuel</th><th className="p-3">Maintenance</th><th className="p-3">Total</th><th className="p-3">Cost / km</th><th className="p-3">Open fuel</th></tr></thead><tbody>{top.map(v=><tr key={v.id} className="border-b border-slate-900 hover:bg-slate-900"><td className="p-3 font-mono text-white">{v.registration_number}<div className="text-[10px] text-slate-500">{v.asset_number||'—'}</div></td><td className="p-3 font-mono">{num(v.distance_km).toLocaleString()} km</td><td className="p-3">{money(v.fuel_cost)}</td><td className="p-3">{money(v.maintenance_cost)}</td><td className="p-3 font-semibold text-white">{money(v.total_cost)}</td><td className="p-3 font-mono text-cyan-300">{money(v.cost_per_km)}</td><td className="p-3">{num(v.open_fuel_anomalies)>0?<span className="text-amber-300">{v.open_fuel_anomalies}</span>:<span className="text-emerald-300">0</span>}</td></tr>)}</tbody></table></div>}</section>
  </>}
 </div>;
};
