import React, { useEffect, useState } from 'react';
import { Activity, AlertTriangle, Car, CircleDollarSign, Fuel, Gauge, RefreshCw, ShieldCheck, Wrench } from 'lucide-react';
import { getCostSummary, type CostSummary } from '../services/costApi';
import type { AlertEvent, Vehicle } from '../types/fleet';

const money=(v:number)=>`GMD ${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:0})}`;
const pct=(v:number,total:number)=>total?Math.round(v/total*100):null;

export const ExecutiveKpiDashboard:React.FC<{vehicles:Vehicle[];alerts:AlertEvent[];onNavigate:(tab:string)=>void}>=({vehicles,alerts,onNavigate})=>{
  const[cost,setCost]=useState<CostSummary|null>(null);
  const[costError,setCostError]=useState('');
  const[loading,setLoading]=useState(true);

  const load=async()=>{setLoading(true);setCostError('');try{setCost((await getCostSummary()).data);}catch(error){setCost(null);setCostError(error instanceof Error?error.message:'Unable to load financial data.');}finally{setLoading(false);}};

  useEffect(()=>{void load();},[]);
  const total=vehicles.length,moving=vehicles.filter(v=>v.status==='moving').length,idling=vehicles.filter(v=>v.status==='idling').length,offline=vehicles.filter(v=>v.status==='offline'||v.status==='no_gps').length,emergency=vehicles.filter(v=>v.status==='emergency').length,unack=alerts.filter(a=>!a.acknowledged).length;
  const hasFleetData=total>0;
  const utilization=pct(moving,total),availability=pct(total-offline,total);

  return <div className="h-full overflow-y-auto p-4 sm:p-6 bg-slate-950 text-slate-100 space-y-5">
    <div className="flex items-center justify-between"><div><div className="text-[10px] uppercase tracking-wider text-cyan-400 font-mono">Government Fleet Executive View</div><h1 className="text-2xl font-bold text-white mt-1">Executive KPI Dashboard</h1><p className="text-xs text-slate-400 mt-1">Live operational and financial indicators sourced from the fleet platform.</p></div><button onClick={()=>void load()} className="p-2 rounded-lg border border-slate-700 bg-slate-900 text-slate-300" title="Refresh live data"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/></button></div>

    {!hasFleetData&&!loading&&<section className="rounded-xl border border-amber-900/60 bg-amber-950/20 p-5"><div className="text-sm font-semibold text-amber-200">No live fleet data available</div><p className="text-xs text-amber-300/70 mt-1">The dashboard will not display invented vehicle counts or KPI values. Register vehicles and connect telemetry to populate this view.</p><button onClick={()=>onNavigate('fleet')} className="mt-3 text-xs font-semibold text-cyan-400">Open Fleet Registry →</button></section>}

    <div className="grid grid-cols-2 xl:grid-cols-6 gap-3"><K label="Fleet" value={hasFleetData?total:'—'} sub={hasFleetData?`${moving} moving`:'No live vehicles'} icon={Car}/><K label="Utilization" value={utilization===null?'—':`${utilization}%`} sub={hasFleetData?`${moving} moving now`:'Awaiting telemetry'} icon={Activity}/><K label="Availability" value={availability===null?'—':`${availability}%`} sub={hasFleetData?`${offline} offline / no GPS`:'Awaiting telemetry'} icon={Gauge}/><K label="Safety exposure" value={hasFleetData?unack:'—'} sub={hasFleetData?`${emergency} emergency`:'No live fleet data'} icon={ShieldCheck}/><K label="Fleet cost" value={cost?money(cost.total_cost):'—'} sub={cost?`${money(cost.cost_per_km)} / km`:'No financial data'} icon={CircleDollarSign}/><K label="Fuel integrity" value={cost?cost.open_fuel_anomalies:'—'} sub={cost?'Open anomalies':'No fuel data'} icon={Fuel}/></div>

    <div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><section className="lg:col-span-2 rounded-xl border border-slate-800 bg-slate-900/70 p-4"><div className="flex items-center justify-between mb-4"><div><h2 className="text-xs font-bold uppercase tracking-wider text-white">Operational Readiness</h2><p className="text-[10px] text-slate-500 mt-1">Current fleet disposition from live vehicle records and telemetry.</p></div><button onClick={()=>onNavigate('tracking')} className="text-[10px] text-cyan-400">Open Live Map →</button></div>{hasFleetData?<div className="space-y-4"><Bar label="Moving" value={moving} total={total} text={`${moving} vehicles`}/><Bar label="Idling" value={idling} total={total} text={`${idling} vehicles`}/><Bar label="Offline / no GPS" value={offline} total={total} text={`${offline} vehicles`}/><Bar label="Emergency" value={emergency} total={total} text={`${emergency} vehicles`}/></div>:<Empty text="No vehicle telemetry is available."/>}</section><section className="rounded-xl border border-slate-800 bg-slate-900/70 p-4"><h2 className="text-xs font-bold uppercase tracking-wider text-white">Executive Actions</h2><div className="mt-3 space-y-2"><Action title="Cost & Financial Intelligence" detail="Open actual expenditure and budget controls" onClick={()=>onNavigate('cost')} icon={CircleDollarSign}/><Action title="Fuel & Loss Intelligence" detail="Open recorded fuel transactions and anomalies" onClick={()=>onNavigate('fuel')} icon={Fuel}/><Action title="Maintenance Control" detail="Open recorded maintenance activity" onClick={()=>onNavigate('maintenance')} icon={Wrench}/><Action title="Alerts & Security" detail={`${unack} unacknowledged recorded events`} onClick={()=>onNavigate('alerts')} icon={AlertTriangle}/></div></section></div>

    <section className="rounded-xl border border-slate-800 bg-slate-900/70 p-4"><div className="flex items-center justify-between"><div><h2 className="text-xs font-bold uppercase tracking-wider text-white">Financial Performance</h2><p className="text-[10px] text-slate-500 mt-1">Actual fuel and maintenance expenditure recorded by the platform.</p></div><button onClick={()=>onNavigate('cost')} className="text-[10px] text-cyan-400">Open Financial Intelligence →</button></div>{costError?<div className="mt-4 rounded-lg border border-rose-900 bg-rose-950/30 p-3 text-xs text-rose-300">Unable to load financial data: {costError}</div>:cost?<div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4"><Metric label="Fuel spend" value={money(cost.fuel_cost)}/><Metric label="Maintenance" value={money(cost.maintenance_cost)}/><Metric label="Total spend" value={money(cost.total_cost)}/><Metric label="Cost / km" value={money(cost.cost_per_km)}/></div>:<Empty text="No financial records are available."/>}</section>
  </div>;
};
function K({label,value,sub,icon:Icon}:{label:string;value:React.ReactNode;sub:string;icon:React.ElementType}){return <div className="rounded-xl border border-slate-800 bg-slate-900/70 p-4"><div className="flex justify-between text-[10px] uppercase text-slate-500"><span>{label}</span><Icon className="w-4 h-4 text-cyan-400"/></div><div className="mt-2 text-2xl font-mono font-bold text-white">{value}</div><div className="mt-1 text-[10px] text-slate-500">{sub}</div></div>}
function Bar({label,value,total,text}:{label:string;value:number;total:number;text:string}){return <div><div className="flex justify-between text-[11px] mb-1"><span className="text-slate-300">{label}</span><span className="font-mono text-slate-500">{text}</span></div><div className="h-2 rounded-full bg-slate-800 overflow-hidden"><div className="h-full bg-cyan-500" style={{width:`${pct(value,total)||0}%`}}/></div></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-slate-950 p-3"><div className="text-[10px] uppercase text-slate-500">{label}</div><div className="mt-1 font-mono font-bold text-white">{value}</div></div>}
function Action({title,detail,onClick,icon:Icon}:{title:string;detail:string;onClick:()=>void;icon:React.ElementType}){return <button onClick={onClick} className="w-full flex items-center gap-3 rounded-lg border border-slate-800 bg-slate-950 p-3 text-left hover:border-slate-700"><Icon className="w-4 h-4 text-cyan-400"/><span className="min-w-0"><span className="block text-xs font-semibold text-white">{title}</span><span className="block text-[10px] text-slate-500">{detail}</span></span></button>}
function Empty({text}:{text:string}){return <div className="rounded-lg border border-slate-800 bg-slate-950/60 p-4 text-xs text-slate-500">{text}</div>}
