import React, { useEffect, useState } from 'react';
import { Building2, KeyRound, ShieldCheck, Users, Plus, Save } from 'lucide-react';
import { AdminAgency, AdminDepartment, AdminPermission, AdminRole, AdminUser, createAdminAgency, createAdminDepartment, createAdminRole, createAdminUser, getAdminAgencies, getAdminDepartments, getAdminPermissions, getAdminRoles, getAdminUsers, updateAdminRolePermissions, updateAdminUserRoles } from '../services/api';

const inputClass = 'w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white outline-none focus:border-cyan-500';
const cardClass = 'rounded-xl border border-slate-800 bg-slate-900/60 p-4';

export const PlatformAdministrationView: React.FC = () => {
  const [tab, setTab] = useState<'agencies'|'departments'|'users'|'roles'>('agencies');
  const [agencies, setAgencies] = useState<AdminAgency[]>([]);
  const [departments, setDepartments] = useState<AdminDepartment[]>([]);
  const [users, setUsers] = useState<AdminUser[]>([]);
  const [roles, setRoles] = useState<AdminRole[]>([]);
  const [permissions, setPermissions] = useState<AdminPermission[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [agencyForm, setAgencyForm] = useState({ name: '', code: '' });
  const [departmentForm, setDepartmentForm] = useState({ agencyId: '', name: '', code: '' });
  const [userForm, setUserForm] = useState({ username: '', email: '', fullName: '', password: '', agencyId: '', departmentId: '', roleId: '' });
  const [roleForm, setRoleForm] = useState({ name: '', description: '', permissionIds: [] as string[] });

  const load = async () => { setLoading(true); setError(''); try { const [a,d,u,r,p] = await Promise.all([getAdminAgencies(), getAdminDepartments(), getAdminUsers(), getAdminRoles(), getAdminPermissions()]); setAgencies(a); setDepartments(d); setUsers(u); setRoles(r); setPermissions(p); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);

  const submitAgency = async (e: React.FormEvent) => { e.preventDefault(); try { await createAdminAgency(agencyForm); setAgencyForm({ name:'', code:'' }); await load(); } catch(e) { setError(e instanceof Error ? e.message : String(e)); } };
  const submitDepartment = async (e: React.FormEvent) => { e.preventDefault(); try { await createAdminDepartment(departmentForm); setDepartmentForm({ ...departmentForm, name:'', code:'' }); await load(); } catch(e) { setError(e instanceof Error ? e.message : String(e)); } };
  const submitUser = async (e: React.FormEvent) => { e.preventDefault(); try { await createAdminUser({ username:userForm.username, email:userForm.email, fullName:userForm.fullName, password:userForm.password, agencyId:userForm.agencyId || null, departmentId:userForm.departmentId || null, roleIds:userForm.roleId ? [userForm.roleId] : [] }); setUserForm({ username:'', email:'', fullName:'', password:'', agencyId:'', departmentId:'', roleId:'' }); await load(); } catch(e) { setError(e instanceof Error ? e.message : String(e)); } };
  const submitRole = async (e: React.FormEvent) => { e.preventDefault(); try { await createAdminRole(roleForm); setRoleForm({ name:'', description:'', permissionIds:[] }); await load(); } catch(e) { setError(e instanceof Error ? e.message : String(e)); } };
  const togglePermission = (id: string) => setRoleForm((f) => ({ ...f, permissionIds: f.permissionIds.includes(id) ? f.permissionIds.filter((x) => x !== id) : [...f.permissionIds, id] }));

  return <div className="flex-1 overflow-y-auto p-5 md:p-7 bg-slate-950">
    <div className="max-w-7xl mx-auto space-y-5">
      <div><div className="flex items-center gap-3"><ShieldCheck className="w-7 h-7 text-cyan-400"/><div><h1 className="text-2xl font-bold text-white">Platform Administration</h1><p className="text-sm text-slate-400">National-level control of agencies, users, roles, permissions and organizational scope.</p></div></div></div>
      {error && <div className="rounded-lg border border-red-800 bg-red-950/50 px-4 py-3 text-sm text-red-300">{error}</div>}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3"><div className={cardClass}><Building2 className="w-5 h-5 text-cyan-400"/><div className="text-2xl font-bold mt-2">{agencies.length}</div><div className="text-xs text-slate-500">Agencies</div></div><div className={cardClass}><Users className="w-5 h-5 text-cyan-400"/><div className="text-2xl font-bold mt-2">{users.length}</div><div className="text-xs text-slate-500">Users</div></div><div className={cardClass}><ShieldCheck className="w-5 h-5 text-cyan-400"/><div className="text-2xl font-bold mt-2">{roles.length}</div><div className="text-xs text-slate-500">Roles</div></div><div className={cardClass}><KeyRound className="w-5 h-5 text-cyan-400"/><div className="text-2xl font-bold mt-2">{permissions.length}</div><div className="text-xs text-slate-500">Permissions</div></div></div>
      <div className="flex gap-2 border-b border-slate-800 overflow-x-auto">{([['agencies','Agencies'],['departments','Departments'],['users','Users'],['roles','Roles & Permissions']] as const).map(([id,label]) => <button key={id} onClick={() => setTab(id)} className={`px-4 py-2 text-sm font-medium border-b-2 ${tab===id?'border-cyan-400 text-cyan-300':'border-transparent text-slate-400 hover:text-white'}`}>{label}</button>)}</div>
      {loading ? <div className="py-16 text-center text-slate-500">Loading administration data…</div> : <>
        {tab==='agencies' && <div className="grid lg:grid-cols-[360px_1fr] gap-5"><form onSubmit={submitAgency} className={cardClass+' space-y-3'}><h2 className="font-semibold">Create Agency</h2><input className={inputClass} placeholder="Agency name" value={agencyForm.name} onChange={e=>setAgencyForm({...agencyForm,name:e.target.value})} required/><input className={inputClass} placeholder="Code e.g. MOT" value={agencyForm.code} onChange={e=>setAgencyForm({...agencyForm,code:e.target.value})} required/><button className="w-full flex items-center justify-center gap-2 rounded-lg bg-cyan-600 px-3 py-2 text-sm font-semibold text-white hover:bg-cyan-500"><Plus className="w-4 h-4"/>Create Agency</button></form><div className="space-y-2">{agencies.map(a=><div key={a.id} className={cardClass+' flex items-center justify-between'}><div><div className="font-semibold">{a.name}</div><div className="text-xs text-slate-500">{a.code} · {a.user_count} users · {a.vehicle_count} vehicles</div></div><span className={`text-xs ${a.active?'text-emerald-400':'text-red-400'}`}>{a.active?'Active':'Inactive'}</span></div>)}{!agencies.length&&<div className="text-slate-500 text-sm">No agencies configured.</div>}</div></div>}
        {tab==='departments' && <div className="grid lg:grid-cols-[360px_1fr] gap-5"><form onSubmit={submitDepartment} className={cardClass+' space-y-3'}><h2 className="font-semibold">Create Department</h2><select className={inputClass} value={departmentForm.agencyId} onChange={e=>setDepartmentForm({...departmentForm,agencyId:e.target.value})} required><option value="">Select agency</option>{agencies.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><input className={inputClass} placeholder="Department name" value={departmentForm.name} onChange={e=>setDepartmentForm({...departmentForm,name:e.target.value})} required/><input className={inputClass} placeholder="Code" value={departmentForm.code} onChange={e=>setDepartmentForm({...departmentForm,code:e.target.value})} required/><button className="w-full flex items-center justify-center gap-2 rounded-lg bg-cyan-600 px-3 py-2 text-sm font-semibold"><Plus className="w-4 h-4"/>Create Department</button></form><div className="space-y-2">{departments.map(d=><div key={d.id} className={cardClass}><div className="font-semibold">{d.name}</div><div className="text-xs text-slate-500">{d.code} · {d.agency_name}</div></div>)}</div></div>}
        {tab==='users' && <div className="grid lg:grid-cols-[390px_1fr] gap-5"><form onSubmit={submitUser} className={cardClass+' space-y-3'}><h2 className="font-semibold">Create User</h2><input className={inputClass} placeholder="Full name" value={userForm.fullName} onChange={e=>setUserForm({...userForm,fullName:e.target.value})} required/><input className={inputClass} placeholder="Username" value={userForm.username} onChange={e=>setUserForm({...userForm,username:e.target.value})} required/><input className={inputClass} type="email" placeholder="Email" value={userForm.email} onChange={e=>setUserForm({...userForm,email:e.target.value})} required/><input className={inputClass} type="password" placeholder="Temporary password (14+ chars)" value={userForm.password} onChange={e=>setUserForm({...userForm,password:e.target.value})} required/><select className={inputClass} value={userForm.agencyId} onChange={e=>setUserForm({...userForm,agencyId:e.target.value,departmentId:''})}><option value="">National / no agency</option>{agencies.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select className={inputClass} value={userForm.departmentId} onChange={e=>setUserForm({...userForm,departmentId:e.target.value})}><option value="">No department</option>{departments.filter(d=>!userForm.agencyId||d.agency_id===userForm.agencyId).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><select className={inputClass} value={userForm.roleId} onChange={e=>setUserForm({...userForm,roleId:e.target.value})}><option value="">No role</option>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><button className="w-full flex items-center justify-center gap-2 rounded-lg bg-cyan-600 px-3 py-2 text-sm font-semibold"><Plus className="w-4 h-4"/>Create User</button></form><div className="space-y-2">{users.map(u=><div key={u.id} className={cardClass+' flex items-center justify-between gap-4'}><div><div className="font-semibold">{u.full_name}</div><div className="text-xs text-slate-500">@{u.username} · {u.email}</div><div className="text-xs text-cyan-400 mt-1">{u.agency_name||'National'} · {u.department_name||'All departments'} · {u.roles.map(r=>r.name).join(', ')||'No role'}</div></div><span className="text-xs text-emerald-400">{u.status}</span></div>)}</div></div>}
        {tab==='roles' && <div className="grid lg:grid-cols-[420px_1fr] gap-5"><form onSubmit={submitRole} className={cardClass+' space-y-3'}><h2 className="font-semibold">Create Role</h2><input className={inputClass} placeholder="Role name" value={roleForm.name} onChange={e=>setRoleForm({...roleForm,name:e.target.value})} required/><input className={inputClass} placeholder="Description" value={roleForm.description} onChange={e=>setRoleForm({...roleForm,description:e.target.value})}/><div className="max-h-80 overflow-y-auto space-y-1">{permissions.map(p=><label key={p.id} className="flex items-start gap-2 rounded-lg px-2 py-1.5 hover:bg-slate-800"><input type="checkbox" checked={roleForm.permissionIds.includes(p.id)} onChange={()=>togglePermission(p.id)} className="mt-1"/><span><span className="block text-xs text-white">{p.name}</span><span className="block text-[10px] text-slate-500">{p.description}</span></span></label>)}</div><button className="w-full flex items-center justify-center gap-2 rounded-lg bg-cyan-600 px-3 py-2 text-sm font-semibold"><Save className="w-4 h-4"/>Create Role</button></form><div className="space-y-2">{roles.map(r=><div key={r.id} className={cardClass}><div className="font-semibold">{r.name}</div><div className="text-xs text-slate-500 mb-2">{r.description}</div><div className="flex flex-wrap gap-1">{r.permissions.map(p=><span key={p.id} className="rounded bg-slate-800 px-2 py-1 text-[10px] text-cyan-300">{p.name}</span>)}</div></div>)}</div></div>}
      </>}
    </div>
  </div>;
};

export default PlatformAdministrationView;
