import React, { useEffect, useState } from 'react';
import { UserRound } from 'lucide-react';
import { getVehicles, getLatestTelemetry, getAlerts, getTrips, getMaintenance, mapVehicle, subscribeToFleetEvents, acknowledgeAlert as apiAcknowledgeAlert, logout as apiLogout, type ApiUser, type FleetEvent, type MaintenanceRecord } from './services/api';
import { Vehicle, Geofence, AlertEvent, Trip, FuelLogEvent, MaintenanceItem, AuditLog, GovernmentAgency } from './types/fleet';
import { Sidebar } from './components/Sidebar';
import { MapView } from './components/MapView';
import { FleetListPanel } from './components/FleetListPanel';
import { DashboardOverview } from './components/DashboardOverview';
import { ExecutiveKpiDashboard } from './components/ExecutiveKpiDashboard';
import { VehicleDetailModal } from './components/VehicleDetailModal';
import { TripPlaybackModal } from './components/TripPlaybackModal';
import { FuelMonitoringView } from './components/FuelMonitoringView';
import { GeofencingView } from './components/GeofencingView';
import { DriverSafetyView } from './components/DriverSafetyView';
import { MaintenanceView } from './components/MaintenanceView';
import { AlertsView } from './components/AlertsView';
import { ReportsView } from './components/ReportsView';
import { AuditSecurityView } from './components/AuditSecurityView';
import { FleetRegistryView } from './components/FleetRegistryView';
import { GpsDevicesView } from './components/GpsDevicesView';
import { DriverMobileModal } from './components/DriverMobileModal';
import { DriverAssignmentModal } from './components/DriverAssignmentModal';
import { CostFinancialView } from './components/CostFinancialView';

function mapApiAlert(row: any): AlertEvent { return { id: String(row.id), vehicleId: String(row.vehicleId), vehicleReg: String(row.registrationNumber || ''), department: 'All Agencies', type: row.type, severity: row.severity, title: String(row.title || row.type), message: String(row.message || ''), timestamp: String(row.occurredAt), location: { lat: Number(row.metadata?.latitude || 0), lng: Number(row.metadata?.longitude || 0), address: '' }, acknowledged: Boolean(row.acknowledgedAt), dispatchedToPolice: Boolean(row.metadata?.dispatchedToPolice) }; }
const VEHICLE_STATUSES: Vehicle['status'][] = ['moving','stopped','idling','parked','offline','no_gps','emergency','unauthorized'];
function asBoolean(value: unknown, fallback: boolean): boolean { if (typeof value === 'boolean') return value; if (typeof value === 'string') { if (value.toLowerCase() === 'true') return true; if (value.toLowerCase() === 'false') return false; } return fallback; }
function applyTelemetryEvent(vehicle: Vehicle, event: FleetEvent): Vehicle { const p=event.payload; const latitude=Number(p.latitude),longitude=Number(p.longitude),speedKmh=Number(p.speedKmh),heading=Number(p.heading),odometerKm=Number(p.odometerKm),fuelLitres=Number(p.fuelLitres); const status=typeof p.status==='string'&&VEHICLE_STATUSES.includes(p.status as Vehicle['status'])?p.status as Vehicle['status']:vehicle.status; const fuel=Number.isFinite(fuelLitres)?fuelLitres:vehicle.currentFuelLiters; return {...vehicle,status,currentLocation:{...vehicle.currentLocation,lat:Number.isFinite(latitude)?latitude:vehicle.currentLocation.lat,lng:Number.isFinite(longitude)?longitude:vehicle.currentLocation.lng},speedKmh:Number.isFinite(speedKmh)?speedKmh:vehicle.speedKmh,heading:Number.isFinite(heading)?heading:vehicle.heading,ignition:asBoolean(p.ignition,vehicle.ignition),mileageKm:Number.isFinite(odometerKm)?odometerKm:vehicle.mileageKm,currentFuelLiters:fuel,currentFuelPercentage:vehicle.tankCapacityLiters>0?Math.max(0,Math.min(100,Math.round(fuel/vehicle.tankCapacityLiters*100))):vehicle.currentFuelPercentage,gpsStatus:'Connected',lastCommunication:event.occurredAt}; }
function mapTrip(row: any): Trip { return { id:String(row.id), vehicleId:String(row.vehicle_id), vehicleReg:String(row.registration_number||''), driverName:String(row.driver_name||'Unassigned'), startTime:String(row.started_at), endTime:String(row.ended_at||''), startLocation:row.start_lat!=null&&row.start_lng!=null?`${row.start_lat}, ${row.start_lng}`:'', endLocation:row.end_lat!=null&&row.end_lng!=null?`${row.end_lat}, ${row.end_lng}`:'', distanceKm:Number(row.distance_km||0), durationMinutes:Number(row.duration_seconds||0)/60, maxSpeedKmh:Number(row.max_speed_kmh||0), avgSpeedKmh:Number(row.average_speed_kmh||0), idleMinutes:Number(row.idle_seconds||0)/60, fuelConsumedLiters:Number(row.fuel_consumed_litres||0), waypoints:[] }; }
function mapMaintenance(row: MaintenanceRecord): MaintenanceItem { const statusMap:Record<MaintenanceRecord['status'],MaintenanceItem['status']>={scheduled:'Scheduled',due_soon:'Due Soon',overdue:'Overdue',completed:'Completed',in_progress:'Due Soon',cancelled:'Completed'}; return { id:row.id, vehicleId:row.vehicle_id, vehicleReg:row.registration_number, category:(row.category||'General servicing') as MaintenanceItem['category'], status:statusMap[row.status]||'Scheduled', dueMileageKm:Number(row.due_odometer_km||0), dueDate:row.due_at||'', costEstimated:Number(row.estimated_cost||0), serviceCenter:row.service_provider||'', notes:row.notes||'' }; }

export function App({ authUser }: { authUser: ApiUser }) {
 const [vehicles,setVehicles]=useState<Vehicle[]>([]); const [alerts,setAlerts]=useState<AlertEvent[]>([]); const [fuelLogs]=useState<FuelLogEvent[]>([]); const [auditLogs]=useState<AuditLog[]>([]); const [geofences]=useState<Geofence[]>([]); const [trips,setTrips]=useState<Trip[]>([]); const [maintenance,setMaintenance]=useState<MaintenanceItem[]>([]); const [activeTab,setActiveTab]=useState<string>('executive'); const [selectedAgency]=useState<GovernmentAgency>('All Agencies'); const [isMobileModalOpen,setIsMobileModalOpen]=useState(false); const [selectedVehicleId,setSelectedVehicleId]=useState<string|null>(null); const [isDossierOpen,setIsDossierOpen]=useState(false); const [isAssignmentOpen,setIsAssignmentOpen]=useState(false); const [activePlaybackTrip,setActivePlaybackTrip]=useState<Trip|null>(null); const [loading,setLoading]=useState(true); const [loadError,setLoadError]=useState<string|null>(null);
 const loadFleet=async()=>{setLoadError(null);try{const [vehicleResult,telemetryResult,alertResult,tripResult,maintenanceResult]=await Promise.all([getVehicles({page:1,limit:100}),getLatestTelemetry(),getAlerts({page:1,limit:100}),getTrips({page:1,limit:200}),getMaintenance({limit:200})]);const telemetryByVehicle=new Map(telemetryResult.data.map(row=>[String(row.vehicle_id),row]));setVehicles(vehicleResult.data.map(row=>mapVehicle(row,telemetryByVehicle.get(row.id))));setAlerts(alertResult.data.map(mapApiAlert));setTrips(tripResult.data.map(mapTrip));setMaintenance(maintenanceResult.data.map(mapMaintenance));}catch(error){console.error('QTS backend load failed',error);setLoadError(error instanceof Error?error.message:'Unable to load fleet data');}finally{setLoading(false);}};
 useEffect(()=>{void loadFleet();const unsubscribe=subscribeToFleetEvents((event)=>{if(event.type==='telemetry.updated'){const vehicleId=String(event.payload.vehicleId||'');if(!vehicleId)return;setVehicles(current=>current.map(vehicle=>vehicle.id===vehicleId?applyTelemetryEvent(vehicle,event):vehicle));return;}if(event.type==='vehicle.updated'){void loadFleet();return;}if(event.type==='alert.created'){setAlerts(current=>[mapApiAlert(event.payload),...current].slice(0,100));}},error=>console.error('QTS realtime stream error',error));return unsubscribe;},[]);
 const filteredVehicles=vehicles; const selectedVehicle=vehicles.find(v=>v.id===selectedVehicleId)||null; const handleSelectVehicle=(id:string)=>{setSelectedVehicleId(id);setIsDossierOpen(true)}; const handleNavigateToTracking=(vehicleId?:string)=>{if(vehicleId)setSelectedVehicleId(vehicleId);setActiveTab('tracking')}; const handleTriggerSOS=(_vehicleId:string)=>{}; const handleTriggerFuelTheft=(_vehicleId:string)=>{}; const handleTriggerRefuel=(_vehicleId:string)=>{}; const handleAcknowledgeAlert=(alertId:string)=>{void apiAcknowledgeAlert(alertId).then(()=>setAlerts(items=>items.map(a=>a.id===alertId?{...a,acknowledged:true}:a))).catch(console.error)}; const handleDispatchPolice=(_alertId:string)=>{}; const handleAddGeofence=(_geo:Geofence)=>{}; const handleDeleteGeofence=(_id:string)=>{}; const handleAddMaintenance=(_item:MaintenanceItem)=>{}; const handleReplayVehicleTrip=(vehicle:Vehicle)=>{const existingTrip=trips.find(t=>t.vehicleId===vehicle.id)||trips.find(t=>t.vehicleReg===vehicle.regNumber);if(existingTrip){setIsDossierOpen(false);setActivePlaybackTrip(existingTrip)}}; const handleLogout=async()=>{await apiLogout();window.location.reload()}; const refreshAfterAssignment=()=>{void loadFleet()};
 return <div className="flex flex-row h-screen w-screen bg-slate-50 text-slate-900 overflow-hidden font-sans select-none"><Sidebar activeTab={activeTab} setActiveTab={setActiveTab} selectedAgency={selectedAgency} currentUser={authUser} activeAlerts={alerts} alertCount={alerts.length} onOpenAlerts={()=>setActiveTab('alerts')} onOpenMobileApp={()=>setIsMobileModalOpen(true)} onTriggerSOS={()=>{}} onTriggerFuelTheft={()=>{}} onLogout={handleLogout}/><main className="flex-1 flex flex-col overflow-hidden relative min-w-0 bg-slate-50">{loading&&<div className="absolute top-0 left-0 right-0 z-30 h-1 bg-cyan-500 animate-pulse"/>}{loadError&&<div className="absolute top-3 right-3 z-30 max-w-md px-4 py-3 rounded-lg border border-red-200 bg-red-50 text-red-700 text-xs shadow-sm">Backend connection error: {loadError}</div>}
   {activeTab==='executive'&&<ExecutiveKpiDashboard vehicles={filteredVehicles} alerts={alerts} onNavigate={setActiveTab}/>} {(activeTab==='overview'||activeTab==='dashboard')&&<DashboardOverview vehicles={filteredVehicles} alerts={alerts} fuelLogs={fuelLogs} selectedAgency={selectedAgency} onNavigateToTracking={handleNavigateToTracking} onOpenAlerts={()=>setActiveTab('alerts')} onOpenFuelIntelligence={()=>setActiveTab('fuel')} onOpenDriverSafety={()=>setActiveTab('safety')}/>} {activeTab==='tracking'&&<div className="flex-1 flex flex-col md:flex-row h-full w-full overflow-hidden relative"><div className="w-full md:w-80 lg:w-96 h-64 md:h-full z-10 shrink-0 border-r border-slate-200 bg-white shadow-sm"><FleetListPanel vehicles={filteredVehicles} selectedVehicleId={selectedVehicleId} onSelectVehicle={id=>setSelectedVehicleId(id)} onOpenDossier={veh=>{setSelectedVehicleId(veh.id);setIsDossierOpen(true)}} onInspectVehicle={handleSelectVehicle}/></div><div className="flex-1 h-full relative"><MapView vehicles={filteredVehicles} geofences={geofences} selectedVehicleId={selectedVehicleId} onSelectVehicle={id=>setSelectedVehicleId(id)} onOpenVehicleDossier={veh=>{setSelectedVehicleId(veh.id);setIsDossierOpen(true)}} onReplayTrip={veh=>handleReplayVehicleTrip(veh)}/></div></div>}
    {(activeTab==='fleet'||activeTab==='intelligence')&&<FleetRegistryView vehicles={filteredVehicles} onSelectVehicle={handleSelectVehicle} onOpenDossier={veh=>{setSelectedVehicleId(veh.id);setIsDossierOpen(true)}} onNavigateToMap={handleNavigateToTracking}/>} {activeTab==='fuel'&&<FuelMonitoringView vehicles={filteredVehicles} fuelLogs={fuelLogs} onTriggerFuelTheft={handleTriggerFuelTheft} onTriggerRefuel={handleTriggerRefuel} onSelectVehicle={handleSelectVehicle}/>} {activeTab==='geofences'&&<GeofencingView geofences={geofences} onAddGeofence={handleAddGeofence} onDeleteGeofence={handleDeleteGeofence} onViewOnMap={()=>setActiveTab('tracking')}/>} {(activeTab==='safety'||activeTab==='driver')&&<DriverSafetyView vehicles={filteredVehicles} onSelectVehicle={handleSelectVehicle}/>} {activeTab==='maintenance'&&<MaintenanceView maintenanceList={maintenance} vehicles={filteredVehicles} onAddMaintenance={handleAddMaintenance} onSelectVehicle={handleSelectVehicle}/>} {activeTab==='devices'&&<GpsDevicesView vehicles={filteredVehicles}/>} {activeTab==='alerts'&&<AlertsView alerts={alerts} onAcknowledgeAlert={handleAcknowledgeAlert} onDispatchPolice={handleDispatchPolice} onLocateOnMap={handleNavigateToTracking}/>} {activeTab==='reports'&&<ReportsView trips={trips} vehicles={filteredVehicles} onPlayTrip={trip=>setActivePlaybackTrip(trip)}/>} {(activeTab==='audit'||activeTab==='api')&&<AuditSecurityView auditLogs={auditLogs}/>} {activeTab==='cost'&&<CostFinancialView/>}
  </main>{isDossierOpen&&selectedVehicle&&<VehicleDetailModal vehicle={selectedVehicle} onClose={()=>setIsDossierOpen(false)} onTriggerSOS={handleTriggerSOS} onTriggerFuelTheft={handleTriggerFuelTheft} onTriggerRefuel={handleTriggerRefuel} onPlayTrip={handleReplayVehicleTrip}/>} {isDossierOpen&&selectedVehicle&&<button id="btn-manage-driver-assignment" onClick={()=>setIsAssignmentOpen(true)} className="fixed bottom-6 right-6 z-[55] flex items-center gap-2 px-4 py-3 rounded-xl bg-cyan-700 hover:bg-cyan-600 border border-cyan-500 text-white text-xs font-bold shadow-2xl"><UserRound className="w-4 h-4"/>Manage Driver Assignment</button>} {isAssignmentOpen&&selectedVehicle&&<DriverAssignmentModal vehicle={selectedVehicle} onClose={()=>setIsAssignmentOpen(false)} onChanged={refreshAfterAssignment}/>} {activePlaybackTrip&&<TripPlaybackModal trip={activePlaybackTrip} vehicle={vehicles.find(v=>v.regNumber===activePlaybackTrip.vehicleReg)} onClose={()=>setActivePlaybackTrip(null)}/>} {isMobileModalOpen&&<DriverMobileModal vehicle={selectedVehicle||filteredVehicles[0]||vehicles[0]} onClose={()=>setIsMobileModalOpen(false)} onTriggerSOS={handleTriggerSOS}/>}</div>;
}
export default App;
